#!/bin/bash

module=${1}

mkdir Infraestructure/Web/Flask/rest/$module
cp -r $DOTFILES_PATH/templates/python/Flask-CreateRestModule/* Infraestructure/Web/Flask/rest/$module

sed -i 's/${module_name}/'$module'/g' Infraestructure/Web/Flask/rest/$module/register_blueprint.py
sed -i 's/${module_name}/'$module'/g' Infraestructure/Web/Flask/rest/$module/get/example.py